// Downloads the font feature's variable fonts (upright, wght axis) from Fontsource into src/fonts/ and writes
// src/features/font/faces.ts (file + unicode-range per subset). All fonts are OFL-1.1.
// usage: node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from 'node:fs/promises';

const FONTS = ['plus-jakarta-sans', 'inter', 'geist', 'figtree'];
const SUBSETS = ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'vietnamese'];

await mkdir('src/fonts', { recursive: true });
const faces = {};
for (const id of FONTS) {
  const res = await fetch(`https://api.fontsource.org/v1/fonts/${id}`);
  if (!res.ok) throw new Error(`${id}: ${res.status}`);
  const meta = await res.json();
  faces[id] = { family: meta.family, files: [] };
  for (const sub of SUBSETS.filter((s) => meta.subsets.includes(s))) {
    const file = `${id}-${sub}.woff2`;
    const font = await fetch(`https://cdn.jsdelivr.net/fontsource/fonts/${id}:vf@latest/${sub}-wght-normal.woff2`);
    if (!font.ok) throw new Error(`${file}: ${font.status}`);
    await writeFile(`src/fonts/${file}`, Buffer.from(await font.arrayBuffer()));
    faces[id].files.push({ file, range: meta.unicodeRange[sub] });
    console.log(file);
  }
}
await writeFile('src/features/font/faces.ts', `// Generated by scripts/fetch-fonts.mjs. Do not edit.
export const FACES: Record<string, { family: string; files: { file: string; range: string }[] }> = ${JSON.stringify(faces, null, 2)};
`);
